In [1]:

from numpy import random
from typing import Iterable

#* Створіть прямокутну матрицю A, яка має N рядків і стовпці M з випадковими елементами. 
#* Визначте, скільки негативних елементів міститься в кожному стовпці та в кожному рядку матриці.

N, M = 3, 3

matrix = random.randint(-10, 10, (N, M))
print(f'матриця: \n{matrix}')


def count_negative_numbers(lst: Iterable[Iterable]):
    negatives_numbers_in_rows = []

    for row in matrix:
        counter = 0

        for item in row:
            if item < 0:
                counter += 1

        negatives_numbers_in_rows.append(counter)
    
    return negatives_numbers_in_rows


resoult = count_negative_numbers(matrix)
for i in range(len(resoult)):
    print(f"{i+1} рядок: {resoult[i]} від'ємних чисел")

матриця: 
[[-10  -1  -3]
 [ -6  -3   5]
 [ -4  -8   8]]
1 рядок: 3 від'ємних чисел
2 рядок: 2 від'ємних чисел
3 рядок: 2 від'ємних чисел
